"""Single source of truth for the backend-development curriculum.

Edit THIS file, then run `python backend-development/_tools/build.py` from the repo root
to regenerate CURRICULUM.md and every module README.md.

Status values for STATUS: todo | draft | review | done
"""

# Each module: n, slug, title, prereq (modern-python), depends (backend modules),
# items = [(file-slug, title, difficulty B/I/A), ...]
MODULES = [
 dict(n="01", slug="http-web-fundamentals", title="HTTP & Web Fundamentals",
  prereq="modern-python 11.1-11.5", depends="-",
  items=[
   ("request-response-lifecycle", "Request/response lifecycle - socket to ASGI to handler", "B"),
   ("methods-safety-idempotency", "HTTP methods, safety and idempotency", "B"),
   ("status-codes-and-headers", "Status codes and headers", "B"),
   ("content-negotiation-and-http-caching", "Content negotiation, compression and HTTP caching - ETag, Cache-Control, conditional requests", "I"),
   ("cookies-and-sessions", "Cookies and sessions", "B"),
   ("stateless-vs-stateful", "Stateless vs stateful services", "B"),
   ("connection-lifecycle", "Connection lifecycle - keep-alive, HTTP/1.1 vs 2 vs 3", "I"),
   ("tls-fundamentals", "TLS fundamentals", "I"),
   ("cors", "CORS - preflight, browser security model, misconfiguration", "I"),
   ("reverse-proxies-and-forwarded-headers", "Reverse proxies and load balancers - X-Forwarded-*, trusting proxy headers", "I"),
  ]),
 dict(n="02", slug="api-design-patterns", title="API Design & Patterns",
  prereq="modern-python 18.1, 18.3", depends="01",
  items=[
   ("resource-modelling-and-uri-design", "Resource modelling and URI design", "B"),
   ("rest-vs-rpc-vs-graphql-vs-grpc", "REST vs RPC vs GraphQL vs gRPC", "I"),
   ("api-versioning", "API versioning", "I"),
   ("contract-first-and-openapi", "Contract-first design and OpenAPI", "I"),
   ("pagination", "Pagination - offset, cursor, keyset", "I"),
   ("filtering-sorting-searching", "Filtering, sorting and searching", "B"),
   ("bulk-operations-and-partial-updates", "Bulk operations and partial updates (PATCH)", "I"),
   ("idempotency-keys", "Idempotency and idempotency keys", "I"),
   ("error-responses-rfc-9457", "Standardised error responses - RFC 9457 Problem Details", "B"),
   ("long-running-operations", "Long-running operations - 202 + polling vs webhooks vs SSE", "I"),
   ("webhook-design", "Webhook design - signatures, replay protection, retries, delivery guarantees", "A"),
   ("rate-limiting-as-api-contract", "Rate limiting as an API contract - 429, Retry-After, RateLimit headers", "I"),
   ("deprecation-and-sunset", "API deprecation, compatibility and sunset", "I"),
  ]),
 dict(n="03", slug="fastapi", title="FastAPI",
  prereq="modern-python 5.4, 12.5, 18.4", depends="01, 02",
  items=[
   ("application-structure-and-asgi", "Application structure and ASGI - what uvicorn actually does", "B"),
   ("routing-and-parameters", "Routing and parameters", "B"),
   ("request-response-models", "Request/response models", "B"),
   ("pydantic-v2-in-depth", "Pydantic v2 in depth - validation modes, serialisation, settings", "I"),
   ("dependency-injection", "Dependency injection", "I"),
   ("sync-vs-async-endpoints", "Sync vs async endpoints - the threadpool", "I"),
   ("middleware", "Middleware", "I"),
   ("exception-handling", "Exception handling and error mapping", "I"),
   ("lifespan", "Lifespan and application lifecycle", "I"),
   ("backgroundtasks-vs-workers", "BackgroundTasks vs real workers", "I"),
   ("file-uploads-and-streaming", "File uploads and streaming responses", "I"),
   ("websockets-basics", "WebSockets basics", "I"),
   ("openapi-customisation", "OpenAPI customisation", "B"),
   ("production-deployment", "Production deployment - uvicorn/gunicorn workers, signals, behind a proxy", "A"),
  ]),
 dict(n="04", slug="async-concurrency", title="Async & Concurrency for Backend",
  prereq="modern-python 12.1-12.5", depends="03",
  items=[
   ("event-loop-in-a-server", "The event loop inside a server process", "I"),
   ("blocking-vs-non-blocking-io", "Blocking vs non-blocking I/O - finding the blocking call", "I"),
   ("async-db-and-http-clients", "Async database and HTTP clients - pools and limits", "I"),
   ("request-scoped-state-contextvars", "Request-scoped state - contextvars", "I"),
   ("race-conditions-in-concurrent-requests", "Race conditions in concurrent requests - asyncio.Lock and Queue", "A"),
   ("lost-updates-and-double-writes", "Lost updates and double writes", "A"),
   ("cpu-bound-work", "CPU-bound work and event-loop blocking", "I"),
   ("timeouts-and-cancellation", "Timeouts and cancellation", "A"),
   ("graceful-shutdown", "Graceful shutdown", "A"),
   ("when-async-helps", "When async helps and when it does not", "I"),
  ]),
 dict(n="05", slug="postgresql-data-modeling", title="PostgreSQL & Data Modeling",
  prereq="modern-python 10.1, 10.2, 10.5", depends="04",
  items=[
   ("relational-modelling-and-keys", "Relational modelling and key choice - serial, UUIDv4, UUIDv7", "B"),
   ("normalisation-tradeoffs", "Normalisation and denormalisation tradeoffs", "I"),
   ("constraints-integrity-upsert", "Constraints, data integrity and upsert", "I"),
   ("multi-tenant-data-modelling", "Multi-tenant data modelling", "I"),
   ("indexing", "Indexing", "I"),
   ("explain-analyze", "EXPLAIN and EXPLAIN ANALYZE", "I"),
   ("query-optimisation", "Query optimisation and pg_stat_statements", "A"),
   ("full-text-search-and-pgvector", "Search in Postgres - full-text and pgvector basics", "I"),
   ("connection-pooling-and-pgbouncer", "Connection pooling and PgBouncer", "I"),
   ("transactions-and-acid", "Transactions and ACID", "I"),
   ("isolation-mvcc-vacuum", "Isolation levels, MVCC, bloat and vacuum", "A"),
   ("locks-and-deadlocks", "Locks and deadlocks", "A"),
   ("optimistic-vs-pessimistic", "Optimistic vs pessimistic concurrency control", "A"),
   ("select-for-update-skip-locked", "SELECT FOR UPDATE and SKIP LOCKED", "A"),
   ("jsonb", "JSONB", "I"),
   ("ctes-and-window-functions", "CTEs and window functions", "I"),
   ("partitioning", "Partitioning", "A"),
   ("backup-restore-pitr", "Backup, restore, PITR, RTO and RPO", "I"),
  ]),
 dict(n="06", slug="sqlalchemy-data-access", title="SQLAlchemy & Data Access",
  prereq="modern-python 10.4, 6.3", depends="03, 04, 05",
  items=[
   ("core-vs-orm", "Core vs ORM", "B"),
   ("engine-and-connection-lifecycle", "Engine and connection lifecycle", "I"),
   ("session-lifecycle", "Session lifecycle", "I"),
   ("relationships-and-loading-strategies", "Relationships and loading strategies", "I"),
   ("n-plus-one", "The N+1 problem", "I"),
   ("transactions", "Transactions", "I"),
   ("sync-vs-async-sqlalchemy", "Sync vs async SQLAlchemy - psycopg3 vs asyncpg", "I"),
   ("connection-pool-configuration", "Connection pool configuration", "I"),
   ("fastapi-integration", "FastAPI integration", "I"),
   ("repository-and-unit-of-work", "Repository and Unit of Work", "A"),
   ("bulk-operations-and-raw-sql", "Bulk operations and raw-SQL escape hatches", "I"),
   ("alembic-migrations", "Alembic migrations", "I"),
   ("zero-downtime-migrations", "Zero-downtime and backward-compatible migrations", "A"),
  ]),
 dict(n="07", slug="backend-design-patterns", title="Backend Design Patterns",
  prereq="modern-python 5.4, 16.4", depends="03, 06",
  items=[
   ("layered-architecture", "Layered architecture", "B"),
   ("router-controller-layer", "Router/controller layer", "B"),
   ("service-layer", "Service layer and mapping domain errors to HTTP", "I"),
   ("repository-pattern", "Repository pattern", "I"),
   ("unit-of-work", "Unit of Work", "I"),
   ("dto-vs-domain-vs-persistence", "DTO/API schema vs domain model vs persistence model", "I"),
   ("dependency-injection-as-a-pattern", "Dependency Injection as a general pattern", "I"),
   ("strategy-and-factory", "Strategy and Factory patterns", "I"),
   ("configuration-management", "Configuration management - pydantic-settings, 12-factor", "B"),
   ("when-abstraction-becomes-harmful", "When abstraction becomes harmful", "I"),
  ]),
 dict(n="08", slug="authentication-authorization", title="Authentication & Authorization",
  prereq="modern-python 18.2", depends="03, 06, 07, 10",
  items=[
   ("sessions-vs-tokens", "Sessions vs tokens", "B"),
   ("cookie-security", "Cookie security - SameSite, Secure, HttpOnly, session fixation", "I"),
   ("jwt-architecture-and-pitfalls", "JWT architecture and pitfalls", "I"),
   ("access-and-refresh-tokens", "Access and refresh tokens", "I"),
   ("refresh-token-rotation", "Refresh-token rotation", "A"),
   ("logout-revocation-denylists", "Logout, revocation and denylists", "I"),
   ("oauth2", "OAuth2", "I"),
   ("authorization-code-pkce", "Authorization Code + PKCE", "A"),
   ("client-credentials", "Client Credentials", "I"),
   ("oidc-overview", "OpenID Connect overview", "I"),
   ("api-keys-and-m2m", "API keys and machine-to-machine auth", "I"),
   ("rbac", "RBAC", "I"),
   ("abac", "ABAC", "A"),
   ("resource-ownership", "Resource ownership", "I"),
   ("password-hashing", "Password hashing", "I"),
   ("account-flows", "Account flows - password reset, email verification, MFA overview", "I"),
   ("credential-stuffing-replay-theft", "Credential stuffing, token replay and theft", "A"),
  ]),
 dict(n="09", slug="file-handling-object-storage", title="File Handling & Object Storage",
  prereq="modern-python 8.5", depends="03, 08 (forward-ref 11)",
  items=[
   ("upload-architectures", "Upload architectures", "B"),
   ("presigned-urls", "Direct-to-storage with presigned URLs", "I"),
   ("proxy-through-backend", "Proxy-through-backend", "I"),
   ("s3-storage-and-postgres-metadata", "S3-compatible object storage + metadata in PostgreSQL", "I"),
   ("large-multipart-resumable-uploads", "Large, multipart and resumable uploads", "I"),
   ("file-authorization-and-expiring-links", "File authorization and expiring links", "I"),
   ("cdn-basics", "CDN basics", "I"),
   ("scanning-and-processing-pipelines", "Scanning and processing pipelines", "I"),
  ]),
 dict(n="10", slug="caching-redis", title="Caching & Redis",
  prereq="modern-python 10.5", depends="04, 05",
  items=[
   ("why-caching", "Why caching exists - local vs distributed", "B"),
   ("cache-aside", "Cache-aside", "I"),
   ("write-through", "Write-through", "I"),
   ("write-behind", "Write-behind", "A"),
   ("redis-data-structures", "Redis data structures", "B"),
   ("redis-client-in-production", "Redis client in production - pools, timeouts, pipelining", "I"),
   ("ttl-and-eviction", "TTL and eviction", "I"),
   ("cache-invalidation", "Cache invalidation", "A"),
   ("stampede-thundering-herd-avalanche", "Cache stampede, thundering herd and avalanche", "A"),
   ("cache-penetration", "Cache penetration", "I"),
   ("hot-keys", "Hot keys", "A"),
   ("distributed-locks", "Distributed locks", "A"),
   ("rate-limiting-algorithms", "Rate-limiting algorithms with Redis", "I"),
   ("sessions-in-redis", "Sessions in Redis", "I"),
   ("pubsub-vs-streams", "Pub/Sub vs Streams", "I"),
   ("persistence", "Redis persistence", "I"),
   ("sentinel-and-cluster", "Sentinel and Cluster concepts", "I"),
  ]),
 dict(n="11", slug="background-processing-messaging", title="Background Processing & Messaging",
  prereq="modern-python 12.3, 12.4", depends="04, 05, 06, 10",
  items=[
   ("why-background-processing", "Why background processing exists", "B"),
   ("request-timeout-budgets", "Request timeout budgets", "I"),
   ("job-queues", "Job queues", "B"),
   ("arq-vs-celery", "ARQ vs Celery", "I"),
   ("worker-pools", "Worker pools", "I"),
   ("retries-and-backoff", "Retries and exponential backoff", "I"),
   ("idempotent-tasks-and-consumers", "Idempotent task design and idempotent consumers", "A"),
   ("scheduled-and-periodic-jobs", "Scheduled and periodic jobs", "I"),
   ("queue-vs-pubsub-vs-streaming", "Queue vs Pub/Sub vs Streaming", "I"),
   ("rabbitmq-vs-kafka-vs-nats", "RabbitMQ vs Kafka vs NATS", "I"),
   ("delivery-semantics", "Delivery semantics - at-most-once, at-least-once, exactly-once", "A"),
   ("poison-messages-and-dlq", "Poison messages and dead-letter queues", "I"),
   ("consumer-lag", "Consumer lag", "I"),
   ("backpressure", "Backpressure", "A"),
   ("outbox-pattern", "Outbox pattern", "A"),
   ("job-status-and-results", "Job status and results", "I"),
  ]),
 dict(n="12", slug="real-time-communication", title="Real-Time Communication",
  prereq="modern-python 11.4, 12.5", depends="03, 04, 08, 10",
  items=[
   ("websocket-architecture", "WebSocket architecture", "I"),
   ("connection-lifecycle", "Connection lifecycle", "I"),
   ("authentication-over-websockets", "Authentication over WebSockets", "I"),
   ("sse", "Server-Sent Events", "I"),
   ("long-polling", "Long polling", "B"),
   ("websocket-vs-sse-vs-polling", "WebSocket vs SSE vs polling", "I"),
   ("scaling-across-replicas", "Scaling WebSockets across replicas", "A"),
   ("redis-pubsub-fan-out", "Redis Pub/Sub fan-out", "I"),
   ("reconnection-strategy", "Reconnection strategy", "I"),
   ("backpressure", "Backpressure", "A"),
   ("connection-limits", "Connection limits", "I"),
  ]),
 dict(n="13", slug="testing-backend-systems", title="Testing Backend Systems",
  prereq="modern-python 15.3-15.6", depends="03-12",
  items=[
   ("unit-testing-a-service-layer", "Unit testing a service layer", "B"),
   ("integration-testing", "Integration testing", "I"),
   ("api-testing", "API testing", "I"),
   ("contract-testing", "Contract testing and OpenAPI snapshots", "I"),
   ("database-and-migration-testing", "Database and migration testing", "I"),
   ("isolation-and-test-data-factories", "Test isolation and test-data factories", "I"),
   ("mocking-external-services", "Mocking external services", "I"),
   ("dependency-overrides", "Dependency overrides", "B"),
   ("async-testing", "Async testing", "I"),
   ("websocket-testing", "WebSocket testing", "I"),
   ("background-task-testing", "Background-task testing", "I"),
   ("testcontainers", "Testcontainers", "I"),
   ("load-testing", "Load testing with Locust and k6", "I"),
   ("testing-failure-scenarios", "Testing failure scenarios", "A"),
  ]),
 dict(n="14", slug="docker-ci-cd-deployment", title="Docker, CI/CD & Deployment",
  prereq="modern-python 17.1-17.3", depends="03.14, 06.13, 13",
  items=[
   ("docker-fundamentals", "Docker fundamentals", "B"),
   ("image-layers", "Image layers", "B"),
   ("multi-stage-builds", "Multi-stage builds", "I"),
   ("python-in-a-container", "Python in a container - PID 1, signals, non-root, workers", "I"),
   ("docker-compose", "Docker Compose", "B"),
   ("networking-and-volumes", "Networking and volumes", "B"),
   ("env-vars-and-secrets", "Environment variables and secrets", "I"),
   ("health-checks", "Health checks", "I"),
   ("docker-swarm", "Docker Swarm - services, stacks, secrets, rolling updates", "I"),
   ("github-actions", "GitHub Actions", "B"),
   ("build-test-scan-pipeline", "Build / test / security pipeline", "I"),
   ("migrations-in-the-pipeline", "Migrations in the deploy pipeline", "I"),
   ("blue-green-deployments", "Blue-green deployments", "I"),
   ("canary-deployments", "Canary deployments", "I"),
   ("rolling-deployments", "Rolling deployments", "I"),
   ("feature-flags", "Feature flags", "I"),
   ("zero-downtime-and-rollback", "Zero-downtime deployment and rollback", "A"),
  ]),
 dict(n="15", slug="observability-reliability", title="Observability & Reliability",
  prereq="modern-python 15.10", depends="04.4, 14",
  items=[
   ("structured-logging", "Structured logging in a service", "I"),
   ("correlation-and-request-ids", "Correlation and request IDs", "I"),
   ("metrics", "Metrics", "I"),
   ("red-and-use", "RED and USE methods", "I"),
   ("prometheus", "Prometheus", "I"),
   ("distributed-tracing", "Distributed tracing", "I"),
   ("opentelemetry", "OpenTelemetry", "I"),
   ("health-checks", "Health checks", "B"),
   ("liveness-vs-readiness", "Liveness vs readiness", "I"),
   ("sli-slo-sla", "SLI, SLO and SLA", "I"),
   ("alerting", "Alerting", "I"),
   ("alert-fatigue", "Alert fatigue", "I"),
   ("timeouts", "Timeouts", "I"),
   ("retries-backoff-jitter", "Retries, backoff and jitter", "I"),
   ("circuit-breakers", "Circuit breakers", "A"),
   ("graceful-degradation", "Graceful degradation", "A"),
   ("bulkheads-load-shedding-isolation", "Bulkheads, load shedding and failure isolation", "A"),
   ("incident-response-and-postmortems", "Incident response, runbooks and postmortems", "I"),
  ]),
 dict(n="16", slug="security", title="API & Application Security",
  prereq="modern-python 18.2", depends="01, 03, 08",
  items=[
   ("owasp-api-top-10", "OWASP API Security Top 10", "B"),
   ("injection", "Injection attacks", "I"),
   ("input-validation-and-mass-assignment", "Input validation and mass assignment", "I"),
   ("xss", "XSS", "I"),
   ("csrf", "CSRF", "I"),
   ("ssrf", "SSRF", "I"),
   ("authentication-vulnerabilities", "Authentication vulnerabilities", "I"),
   ("authorization-vulnerabilities-bola-bfla", "Authorization vulnerabilities - BOLA and BFLA", "A"),
   ("abuse-prevention-and-dos", "Abuse prevention and DoS hygiene", "I"),
   ("secrets-management", "Secrets management", "I"),
   ("dependency-and-supply-chain", "Dependency and supply-chain security", "I"),
   ("secure-headers", "Secure headers, including CORS hardening", "I"),
   ("pii-and-audit-logging", "PII handling and audit logging", "I"),
   ("data-deletion-and-privacy", "Data deletion and privacy considerations", "I"),
  ]),
 dict(n="17", slug="performance-scalability", title="Performance & Scalability",
  prereq="modern-python 17.5", depends="05, 06, 10, 13.13, 15",
  items=[
   ("performance-fundamentals", "Performance fundamentals - latency, throughput, percentiles", "B"),
   ("cpu-bound-vs-io-bound", "CPU-bound vs I/O-bound workloads", "I"),
   ("profiling-a-running-service", "Profiling a running service", "I"),
   ("benchmarking", "Benchmarking", "I"),
   ("slow-endpoint-diagnosis", "Slow-endpoint diagnosis - the method", "A"),
   ("data-layer-checklist", "Data-layer checklist - queries, pool, N+1, pagination, caching revisited", "I"),
   ("python-server-tuning", "Python server tuning - workers, uvloop, orjson, GC, memory leaks", "A"),
   ("batch-processing", "Batch processing", "I"),
   ("vertical-vs-horizontal-scaling", "Vertical vs horizontal scaling", "B"),
   ("stateless-services", "Stateless services", "I"),
   ("load-balancing", "Load balancing", "I"),
   ("read-replicas-and-replica-lag", "Read replicas and replica lag", "A"),
   ("sharding-what-changes-in-your-code", "Sharding - what changes in your code", "I"),
   ("capacity-planning-from-load-tests", "Capacity planning from load tests", "I"),
  ]),
 dict(n="18", slug="backend-architecture", title="Backend Architecture",
  prereq="-", depends="07, 11, 15",
  items=[
   ("monolith-modular-monolith-microservices", "Monolith vs modular monolith vs microservices - with a FastAPI modular layout", "I"),
   ("when-not-to-use-microservices", "When NOT to use microservices", "I"),
   ("clean-and-hexagonal", "Clean and Hexagonal architecture - ports and adapters", "A"),
   ("ddd-overview", "Domain-Driven Design overview", "A"),
   ("service-communication", "Service communication - sync vs async", "I"),
   ("api-gateway-and-bff", "API Gateway and BFF", "I"),
   ("multi-tenancy-architectures", "Multi-tenancy architectures", "A"),
   ("event-driven-architecture", "Event-driven architecture", "A"),
   ("cqrs", "CQRS as separate read models", "A"),
  ]),
 dict(n="19", slug="distributed-systems", title="Distributed Systems Fundamentals",
  prereq="modern-python 10.5", depends="11, 15, 18",
  items=[
   ("why-distributed-systems-are-hard", "Why distributed systems are hard", "B"),
   ("network-failures", "Network failures", "I"),
   ("timeouts-and-partial-failure", "Timeouts and partial failure", "I"),
   ("clocks-ordering-and-ids", "Clocks, ordering and IDs", "I"),
   ("cap-in-practice", "CAP theorem in practice", "I"),
   ("consistency-models", "Consistency models", "A"),
   ("eventual-consistency", "Eventual consistency", "I"),
   ("idempotency-and-deduplication", "Idempotency and deduplication end-to-end", "A"),
   ("distributed-transactions-and-2pc", "Distributed transactions and 2PC", "A"),
   ("saga-pattern", "Saga pattern", "A"),
   ("event-sourcing-fundamentals", "Event sourcing fundamentals", "A"),
   ("replication-leaders-consensus", "Replication, leaders and consensus - what a backend engineer needs", "A"),
  ]),
 dict(n="20", slug="production-projects", title="Production Backend Projects",
  prereq="modern-python 19.3, 19.4", depends="all",
  items=[
   ("rate-limited-public-api", "Project 1 - Rate-limited public API", "I"),
   ("authentication-service", "Project 2 - Authentication service", "I"),
   ("event-driven-order-system", "Project 3 - Event-driven order system", "A"),
   ("real-time-notification-system", "Project 4 - Real-time notification system", "A"),
   ("nms-monitoring-backend", "Project 5 - NMS-style monitoring backend", "A"),
   ("reliability-lab", "Optional - Reliability lab: multi-service with tracing, retries, circuit breakers", "A"),
  ]),
]

# Progress: "NN.M" -> status.  Anything not listed is "todo".
STATUS: dict[str, str] = {
    "01.1": "done",
    "01.2": "done",
    "01.3": "done",
    "01.4": "done",
    "01.5": "done",
    "01.6": "done",
    "01.7": "done",
    "01.8": "done",
    "01.9": "done",
    "01.10": "done",
    "02.1": "done",
    "02.2": "done",
    "02.3": "done",
    "02.4": "done",
    "02.5": "done",
    "02.6": "done",
    "02.7": "done",
    "02.8": "done",
    "02.9": "done",
    "02.10": "done",
    "02.11": "done",
    "02.12": "done",
    "02.13": "done",
    "03.1": "done",
    "03.2": "done",
    "03.3": "done",
    "03.4": "done",
    "03.5": "done",
    "03.6": "done",
    "03.7": "done",
    "03.8": "done",
    "03.9": "done",
    "03.10": "done",
    "03.11": "done",
    "03.12": "done",
    "03.13": "done",
    "03.14": "done",
    "04.1": "done",
    "04.2": "done",
    "04.3": "done",
    "04.4": "done",
    "04.5": "done",
    "04.6": "done",
    "04.7": "done",
    "04.8": "done",
    "04.9": "done",
    "04.10": "done",
    "05.1": "draft",
    "05.2": "draft",
    "05.3": "draft",
    "05.4": "draft",
    "05.5": "draft",
    "05.6": "draft",
}
